name: Deploy Node.js project to Azure Function App

on:
  [push, workflow_dispatch]

env:
  AZURE_FUNCTIONAPP_NAME: meetup-aggregator    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'                     # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: Deploy Bicep template
      uses: Azure/arm-deploy@v1.0.8
      with:
        scope: resourcegroup
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: deploy/deploy.bicep
    
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
